### ISSUE TITLE
Does not send request to code server. 

### ISSUE THREAD

**Issue by Israr** [Venthe/vscode-fauxpilot#24]
I am trying to run it with turpopilot. I have turpopilot server running, and have configured fauxpilot to use it. But It does not work. I do not see any network packet going out to my turbopilot server

**Comment by voarsh2** [comment]
I get issues like this:
Error: getaddrinfo ENOTFOUND 32435
	at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)

The URL to the server works in my browser and I get a response.......

**Comment by Venthe** [comment]
Can you please post your (relevant) settings for the fauxpilot extension?

**Comment by Israr** [comment]
`    "fauxpilot.server": "http://192.168.128.4:18080/v1/engines",
    "fauxpilot.enabled": true,
    "fauxpilot.suggestionDelay": 0,
    "fauxpilot.model": "codegen",
`

**Comment by Ghost-Assassin** [comment]
I would recommend you do the following to debug, 
1. restart your vscode after each time you make modification to the plug-in.
2. install a wireshark, observe if there any request is made to the target server 
maybe feedback us the test result from steps above.

**Comment by timothedelion** [comment]
I faced the same symptoms (nothing is sent to the turbopilot server).

And I found this error message in `~/Library/Application\ Support/Code/logs/<timestamp>/window1/exthost/`

```
2023-08-03 18:03:12.363 [error] [Venthe.fauxpilot] provider FAILED
2023-08-03 18:03:12.364 [error] Error: Illegal argument: line must be non-negative
	at v (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:7:1101)
	at new s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:5076)
	at new t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:95:6590)
	at a.FauxpilotCompletionProvider.getPrompt (/Users/timothedelion/.vscode/extensions/venthe.fauxpilot-1.1.6/dist/extension.js:2:75474)
	at a.FauxpilotCompletionProvider.provideInlineCompletionItems (/Users/timothedelion/.vscode/extensions/venthe.fauxpilot-1.1.6/dist/extension.js:2:74185)
	at pe.provideInlineCompletions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:53402)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:71447
	at se.s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:62833)
	at se.$provideInlineCompletions (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:101:71433)
	at t.N (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:11199)
	at t.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:10965)
	at t.H (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:10007)
	at t.G (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:9122)
	at i.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:7952)
	at p.w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:60:1902)
	at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:60:2119)
	at f.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:76:13931)
	at i.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:30341)
	at p.w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:60:1902)
	at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:60:2119)
	at f.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:76:13931)
	at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:28621)
	at MessagePortMain.emit (node:events:513:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367)
```

If it can help

**Comment by ivantor0** [comment]
@timothedelion hi there! In your case the issue may be related to the latest update and specifically the newly added `LEADING_LINES_PROP` parameter, as the code block in `FauxpilotCompletionProvider.getPrompt` at `extension.js:2:75474` derives the lines to be processed from `t.LEADING_LINES_PROP*i` and, as it seems, something can get broken here

**Solution for your specific problem**
If you encounter an error with `line must be non-negative` at `extension.js:2:74185` and `utility_init:2:367`, try **downgrading** vscode-fauxpilot to **version 1.1.5**. I did that and the extension started working just fine
